[options]
admin_passwd = admin123
db_host = /home/runner/.postgres/run
db_user = runner
addons_path = addons
http_interface = 0.0.0.0
http_port = 5000
workers = 0
log_level = warn
proxy_mode = True
list_db = True
