[options]
admin_passwd = admin123
db_host = ep-still-mud-ad8rxj1x.c-2.us-east-1.aws.neon.tech
db_port = 5432
db_user = neondb_owner
db_password = npg_Ib2T3XloYQJy
addons_path = addons
http_interface = 0.0.0.0
http_port = 5000
workers = 0
log_level = warn
proxy_mode = True
list_db = True
