[options]
admin_passwd = admin123
db_host = /home/runner/.postgres/run
db_port = False
db_user = runner
db_password = 
addons_path = addons
http_interface = 0.0.0.0
http_port = 5000
workers = 0
log_level = info
proxy_mode = True
list_db = True
